version: "3"
services:
  nas-tools:
    image: airzui/nastools:latest
    ports:
      - 3000:3000        # 默认的webui控制端口
    volumes:
      - /Users/yilongli/code/nastools/config:/config   # 冒号左边请修改为你想保存配置的路径
      - /Users/yilongli/code/nastools/media:/media   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment: 
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
